# Generated by Django 4.1.1 on 2022-09-14 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('link', models.URLField(blank=True, null=True)),
                ('isOnEveryLesson', models.BooleanField(default=False, verbose_name='Длительное')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('deadlineAt', models.DateTimeField(verbose_name='Дата дедлайна')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
    ]
