# Generated by Django 4.1.1 on 2022-09-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='deadlineAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата дедлайна'),
        ),
    ]
