# Generated by Django 4.1.1 on 2022-09-14 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('READ_USER_PROFILE_SPECIFIC_USERS', 'Read User Profile Specific Users'), ('READ_USER_PROFILE_ANY_USERS_SPECIFIC_COURSES', 'Read User Profile Any Users Specific Courses'), ('UPDATE_USER_PROFILE_SPECIFIC_USERS', 'Update User Profile Specific Users'), ('DELETE_USER_PROFILE_SPECIFIC_USERS', 'Delete User Profile Specific Users'), ('CREATE_HOMEWORK_SPECIFIC_COURSES', 'Create Homework Specific Courses'), ('READ_ASSIGNED_HOMEWORK_SPECIFIC_USERS', 'Read Assigned Homework Specific Users'), ('READ_CREATED_HOMEWORK_SPECIFIC_USERS', 'Read Created Homework Specific Users'), ('UPDATE_HOMEWORK_SPECIFIC_COURSES', 'Update Homework Specific Courses'), ('UPDATE_HOMEWORK_DONE_STATUS_SPECIFIC_USERS', 'Update Homework Done Status Specific Users'), ('DELETE_HOMEWORK_SPECIFIC_COURSES', 'Delete Homework Specific Courses'), ('CREATE_COURSES', 'Create Courses'), ('READ_SPECIFIC_COURSES', 'Read Specific Courses'), ('UPDATE_SPECIFIC_COURSES', 'Update Specific Courses'), ('UPDATE_SPECIFIC_COURSES_MEMBERS', 'Update Specific Courses Members'), ('DELETE_SPECIFIC_COURSES', 'Delete Specific Courses')], max_length=255, verbose_name='Ключ')),
                ('targetUserIdKey', models.CharField(blank=True, choices=[('OWN_ID', 'Own Id'), ('STUDY_COURSES_IDS', 'Study Courses Ids'), ('TEACH_COURSES_IDS', 'Teach Courses Ids')], max_length=255, null=True, verbose_name='Ключ user ID цели доступа')),
                ('targetCourseIdKey', models.CharField(blank=True, choices=[('OWN_ID', 'Own Id'), ('STUDY_COURSES_IDS', 'Study Courses Ids'), ('TEACH_COURSES_IDS', 'Teach Courses Ids')], max_length=255, null=True, verbose_name='Ключ course ID цели доступа')),
                ('targetCourseId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Course ID цели доступа')),
            ],
            options={
                'verbose_name': 'Права',
                'verbose_name_plural': 'Права',
            },
        ),
    ]
